dawaiwala/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('frontend/', include('frontend.urls')),
    path('users/', include('users.urls')),
    path('vendors/', include('vendors.urls')),
    path('api/', include('rest_api.urls')),
    path('', include('store.urls')),
]


store/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from. import views
app_name = 'store'

urlpatterns = [
    path('', views.home, name='store'),
    path('about/', views.about, name='store-about'),
    path('blog/', views.blog, name='store-blog'),
    path('brands/', views.brands, name='store-brands'),
    path('catalog/', views.catalog, name='store-catalog'),
    path('category/', views.category, name='store-category'),
    path('contacts/', views.contacts, name='store-contacts'),
    path('delivery/', views.delivery, name='store-delivery'),
    path('news/', views.news, name='store-news'),
    path('faq/', views.faq, name='store-faq'),
    path('settings/', views.settings, name='store-settings'),


    # path('payment/<payment_option>/', views.PaymentView.as_view(), name='store-payment'),
    path('add-to-compare/<slug>/', views.add_to_compare, name='add-to-compare'),
    path('compare/', views.compare, name='store-compare'),
    path('product/<slug>/', views.product, name='store-product'),
    path('add-to-favorite/<slug>/', views.add_to_favorite, name='add-to-favorite'),
    path('favorites/', views.favorites, name='store-favorites'),
    path('cart/', views.CartView.as_view(), name='store-cart'),
    path('subcategory/', views.shop_view, name='store-subcategory'),

    path('add-to-cart/<slug>/', views.add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/', views.remove_from_cart, name='remove-from-cart'),
    path('remove-single-item-from-cart/<slug>/', views.remove_single_item_from_cart, name='remove-single-item-from-cart'),
    path('category/<slug>/', views.category_view, name='store-category'),
    path('review/<int:pk>/', views.review, name='store-review'),
    path('review/delete/<int:pk>/', views.review_delete, name='store-review-delete'),
    path('product/return/<str:status>/<int:pk>/', views.product_refund, name='store-product-return'),
    path('product/cancel/<int:pk>/', views.product_canceled, name='store-product-cancel'),
    path('product/prescription/upload/', views.prescription_upload, name='store-product-prescription-upload'),
    path('address/', views.customer_address_add, name='store-address'),
    path('address/update/<int:pk>/', views.customer_address_update, name='store-address-update'),
    path('checkout/', views.checkout, name='store-checkout'),
    path('payment/stripe/<int:pk>/', views.PaymentView.as_view(), name='store-payment-stripe'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)




store/forms.py
from django import forms
from .models import Reviews, CustomerLocation, Return, Cancel, CouponCustomer, PrescriptionUpload, CustomerAddress
from mapwidgets.widgets import GooglePointFieldWidget

PAYMENT_CHOICES = (
    ('S', 'Stripe'),
    ('P', 'PayPal')
)


class LocationForm(forms.ModelForm):

    class Meta:
        model = CustomerLocation
        fields = ("location",)
        widgets = {
            'location': GooglePointFieldWidget,
            # 'name': GoogleStaticOverlayMapWidget,
        }


class CheckoutForm(forms.Form):
    shipping_address = forms.CharField(required=False)
    shipping_address2 = forms.CharField(required=False)
    shipping_city = forms.CharField(required=False)
    shipping_postal_code = forms.IntegerField(required=False)
    shipping_phone_number = forms.IntegerField(required=False)

    billing_address = forms.CharField(required=False)
    billing_address2 = forms.CharField(required=False)
    billing_city = forms.CharField(required=False)
    billing_postal_code = forms.IntegerField(required=False)
    billing_phone_number = forms.IntegerField(required=False)

    same_billing_address = forms.BooleanField(required=False)
    set_default_shipping = forms.BooleanField(required=False)
    use_default_shipping = forms.BooleanField(required=False)
    set_default_billing = forms.BooleanField(required=False)
    use_default_billing = forms.BooleanField(required=False)

    payment_option = forms.ChoiceField(
        widget=forms.RadioSelect, choices=PAYMENT_CHOICES)


class CouponForm(forms.Form):
    code = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Promo code'
    }))


class RefundForm(forms.Form):
    ref_code = forms.CharField()
    message = forms.CharField(widget=forms.Textarea(attrs={
        'rows': 4
    }))
    email = forms.EmailField()


class PaymentForm(forms.Form):
    stripeToken = forms.CharField(required=False)
    save = forms.BooleanField(required=False)
    use_default = forms.BooleanField(required=False)


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Reviews
        fields = ('title', 'review_description', 'rating')


class ReturnForm(forms.ModelForm):
    review_description = forms.Textarea()

    class Meta:
        model = Return
        fields = ('return_reason', 'request_return_type', 'review_description')


class CancelForm(forms.ModelForm):
    review_description = forms.Textarea()

    class Meta:
        model = Cancel
        fields = ('cancel_reason', 'request_cancel_type', 'review_description')


class CouponCustomerForm(forms.ModelForm):

    class Meta:
        model = CouponCustomer
        fields = ('code',)


class PrescriptionUploadForm(forms.ModelForm):

    class Meta:
        model = PrescriptionUpload
        fields = ('prescription',)


class CustomerAddressForm(forms.ModelForm):
    shipping_street_address_line_2 = forms.CharField(max_length=100, required=False)
    shipping_phone_number = forms.IntegerField(required=False)

    billing_street_address = forms.CharField(max_length=100, required=False)
    billing_street_address_line_2 = forms.CharField(max_length=100, required=False)
    billing_city = forms.CharField(max_length=100, required=False)
    billing_phone_number = forms.IntegerField(required=False)
    billing_postal_code = forms.IntegerField(required=False)

    class Meta:
        model = CustomerAddress
        fields = ('shipping_street_address', 'shipping_street_address_line_2', 'shipping_city',
                  'shipping_phone_number', 'shipping_postal_code', 'billing_street_address',
                  'billing_street_address_line_2', 'billing_city', 'billing_postal_code', 'billing_phone_number',
                  'shipping_is_billing', 'default')

store/views.py
from django.http import HttpResponseRedirect
from django.views.generic import View
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect
from django.contrib import messages
from django.utils import timezone
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.mixins import LoginRequiredMixin
from django.conf import settings
from django.contrib.gis.geos import Point
from django.contrib.gis.db.models.functions import Distance
from stripe.api_resources.terminal import location

from vendors.models import VendorLocation, VendorAddress, Vendor

from .forms import CheckoutForm, CouponForm, PaymentForm, ReviewForm, LocationForm, ReturnForm, CancelForm, \
                   CouponCustomerForm, PrescriptionUploadForm, CustomerAddressForm
from .models import OrderItem, Order, FavoriteItem, CompareItem, Payment, Coupon, UserProfile, Slide, Reviews, \
                    CustomerLocation, MiniOrder, CouponCustomer, CustomerAddress

from vendors.models import Item, Category, Brands
from users.models import User
from .filters import OrderFilter

import stripe
stripe.api_key = settings.STRIPE_SECRET_KEY


def shop_view(request):
    model = Item.objects.all()

    item_filter = OrderFilter(request.GET, queryset=model)
    model = item_filter.qs
    context = {
        'object_list': model,
        'filter': item_filter
    }
    return render(request, 'store/subcategory.html', context)


def category_view(request, slug):
    model2 = Category.objects.get(title=slug)
    model = Item.objects.filter(category=model2.id)

    context = {
        'object_list': model,
    }
    return render(request, 'store/category_wise.html', context)


def product(request, slug):
    item = Item.objects.get(id=slug)
    related_item = Item.objects.filter(category=item.category)
    variations = Item.objects.filter(variation_id=item.variation_id)
    order_item = OrderItem.objects.filter(user=request.user, ordered=True, item=item)
    reviews = Reviews.objects.filter(item=item)
    try:
        user_review = Reviews.objects.get(item=item, user=request.user)
    except ObjectDoesNotExist:
        user_review = None
    number_of_reviews = len(reviews)

    total_rating = 0
    try:
        for x in reviews:
            total_rating += int(x.rating)
        average_rating = total_rating // number_of_reviews
    except ZeroDivisionError:
        average_rating = 0
    context = {'item': item,
               'variations': variations,
               'related_item': related_item,
               'order_item': order_item,
               'reviews': reviews,
               'number_of_reviews': number_of_reviews,
               'average_rating': average_rating,
               'user_review': user_review,
               }
    return render(request, 'store/product.html', context)


class CartView(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            form = CouponCustomerForm()
            prescription_form = PrescriptionUploadForm(self.request.FILES)
            context = {
                'object': order,
                'form': form,
                'prescription_form': prescription_form,
            }
            return render(self.request, 'store/cart.html', context)
        except ObjectDoesNotExist:
            messages.error(self.request, "You do not have any item in cart")
            return redirect("/")

    def post(self, *args, **kwargs):
        form = CouponCustomerForm(self.request.POST)
        prescription_form = PrescriptionUploadForm(self.request.POST, self.request.FILES)
        order = Order.objects.get(user=self.request.user, ordered=False)

        if prescription_form.is_valid():
            p_form = prescription_form.save(commit=False)
            p_form.user = self.request.user
            p_form.save()
            order.prescription = p_form
            order.save()
            context = {
                'object': order,
                'form': form,
                'prescription_form': prescription_form
            }
            return render(self.request, 'store/cart.html', context)
        if form.is_valid():
                coupon = form.save(commit=False)
            # try:
                coupon = CouponCustomer.objects.get(code=coupon.code, user=self.request.user)
                if coupon.used is True:
                    messages.success(self.request, f'Code Already Used!')
                    context = {
                        'object': order,
                        'form': form,
                        'prescription_form': prescription_form
                    }
                    return render(self.request, 'store/cart.html', context)
                else:
                    coupon.discount_amount = 0
                    coupon.order_amount = order.get_total_without_coupoun()
                    coupon.save()
                    vendor_coupon = Coupon.objects.get(code=coupon.code)
                    if coupon.order_amount >= vendor_coupon.minimum_order_amount:
                        coupon.discount_amount = coupon.order_amount * (vendor_coupon.discount_percent / 100)
                        coupon.applicable = True
                        coupon.save()
                        context = {
                            'object': order,
                            'form': form,
                            'prescription_form': prescription_form
                        }
                        return render(self.request, 'store/cart.html', context)

            # except:
            #     coupon.user = self.request.user
            #     coupon.save()
            #     vendor_coupon = Coupon.objects.get(code=coupon.code)
            #     coupon.coupon = vendor_coupon
            #     coupon.discount_amount = 0
            #     coupon.order_amount = order.get_total_without_coupoun()
            #     coupon.save()
            #     if coupon.order_amount >= vendor_coupon.minimum_order_amount:
            #         coupon.discount_amount = coupon.order_amount * (vendor_coupon.discount_percent / 100)
            #         # coupon.used = True
            #         coupon.applicable = True
            #         coupon.save()
            #
            #     order.coupon_customer = coupon
            #     order.save()
            #     context = {
            #         'object': order,
            #         'form': form,
            #         'prescription_form': prescription_form
            #     }
            #     messages.success(self.request, f'Code Applied!')
            #     return render(self.request, 'store/cart.html', context)
            # finally:
            #     context = {
            #         'object': order,
            #         'form': form,
            #         'prescription_form': prescription_form
            #     }
            #     return render(self.request, 'store/cart.html', context)
        context = {
            'object': order,
            'form': form,
            'prescription_form': prescription_form,
        }
        return render(self.request, 'store/cart.html', context)


class OrderSummaryView(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):
        try:
            user = User.objects.get(id=self.request.user.id)
            order = Order.objects.get(user=self.request.user, ordered=False)
            context = {
                'object': order,
                'user': user,
            }
            return render(self.request, 'store/checkout.html', context)
        except ObjectDoesNotExist:
            messages.error(self.request, "You do not have any item in cart")
            return redirect("/")


@login_required
def add_to_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)
    order_item, created = OrderItem.objects.get_or_create(
        item=item,
        user=request.user,
        ordered=False,
    )
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(item__slug=item.slug).exists():
            if order_item.quantity >= order_item.item.total_stock:
                order_item.quantity = order_item.item.total_stock
            else:
                order_item.quantity += 1
                order_item.save()
                # m_order = MiniOrder.objects.filter(order_ref_number=order.order_ref_number)
                messages.info(request, "Item qty was updated.")
                return redirect("store:store-cart")
        else:
            order.items.add(order_item)
            # order_item.save()
            order.save()

            ordered_date = timezone.datetime.now().strftime('%Y-%m-%d')
            ordered_time = timezone.datetime.now().strftime('%H:%M:%S')

            m_order = MiniOrder.objects.create(
                ordered_date=ordered_date, ordered_time=ordered_time, vendor=item.vendors.first(), user=request.user,
                order_ref_number=order.order_ref_number, order_item=order_item)
            m_order.mini_order_ref_number = f"MORN-{100000 + int(m_order.id)}"
            m_order.save()

            order.mini_order.add(m_order)
            order.save()

    else:
        ordered_date = timezone.datetime.now().strftime('%Y-%m-%d')
        ordered_time = timezone.datetime.now().strftime('%H:%M:%S')
        order = Order.objects.create(
            user=request.user, ordered_date=ordered_date, ordered_time=ordered_time)  # vendor=item.sold_by
        ORN = f"ORN-{100000 + int(order.id)}"
        order.order_ref_number = ORN

store/templates/store/favorites.html
{% extends 'store/base.html' %}
{% load static %}
  {% block content %}
      <main>
        <section class="uk-section uk-section-small">
          <div class="uk-container">
            <div class="uk-grid-medium" uk-grid>
              <div class="uk-width-1-1 uk-width-1-4@m tm-aside-column">
                <div class="uk-card uk-card-default uk-card-small tm-ignore-container" uk-sticky="offset: 90; bottom: true; media: @m;">
                  <div class="uk-card-header">
                    <div class="uk-grid-small uk-child-width-1-1" uk-grid>
                      <section>
                        <div class="uk-width-1-3 uk-width-1-4@s uk-width-1-2@m uk-margin-auto uk-visible-toggle uk-position-relative uk-border-circle uk-overflow-hidden uk-light"><img class="uk-width-1-1" src="images/avatar.jpg"><a class="uk-link-reset uk-overlay-primary uk-position-cover uk-hidden-hover" href="#">
                            <div class="uk-position-center"><span uk-icon="icon: camera; ratio: 1.25;"></span>
                            </div></a></div>
                      </section>
                      <div class="uk-text-center">
                        <div class="uk-h4 uk-margin-remove">{{ user.username }}</div>
                        <div class="uk-text-meta">{{ user.date_joined }}</div>
                      </div>
                      <div>
                        <div class="uk-grid-small uk-flex-center" uk-grid>
                          <div><a class="uk-button uk-button-default uk-button-small" href="settings.html"><span class="uk-margin-xsmall-right" uk-icon="icon: cog; ratio: .75;"></span><span>Settings</span></a></div>
                          <div>
                            <button class="uk-button uk-button-default uk-button-small" href="#" title="Log out"><span uk-icon="icon: sign-out; ratio: .75;"></span>
                            </button>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div>
                    <nav>
                      <ul class="uk-nav uk-nav-default tm-nav">
                        <li><a href="{% url 'users-order' %}">Orders
                            
                            <span>(2)</span></a></li>
                        <li class="uk-active"><a href="{% url 'store:store-favorites' %}">Favorites
                            
                            <span>(3)</span></a></li>
                      </ul>
                    </nav>
                  </div>
                </div>
              </div>
              <div class="uk-width-1-1 uk-width-expand@m">
                <div class="uk-card uk-card-default uk-card-small tm-ignore-container">
                  <header class="uk-card-header">
                    <h1 class="uk-h2">Favorites</h1>
                  </header>

                  {% for item in item %}

                    <div class="uk-grid-collapse tm-products-list" uk-grid>
                      <article class="tm-product-card">
                        <div class="tm-product-card-media">
                          <div class="tm-ratio tm-ratio-4-3"><a class="tm-media-box" href="product.html">
                              <div class="tm-product-card-labels"><span class="uk-label uk-label-warning">{{item.item.label}}</span>
                              </div>
                              <figure class="tm-media-box-wrap"><img src="{{item.item.image_main.url}}" alt="{{item.item.title }}"/>
                              </figure></a></div>
                          &nbsp;</div>
                        <div class="tm-product-card-body">
                          <div class="tm-product-card-info">
                            <div class="uk-text-meta uk-margin-xsmall-bottom">{{item.item.category }}</div>
                            <h3 class="tm-product-card-title"><a class="uk-link-heading" href="product.html">{{item.item.title }}</a></h3>
                            <div class="uk-text-meta uk-margin-xsmall-bottom">{{item.item.short_description }}</div>
                          </div>
                          <div class="tm-product-card-shop">
                            <div class="tm-product-card-prices">
                              {% if item.item.discount_price %}
                                  <del class="uk-text-meta">Rs:{{item.item.price }}</del>
                                  <div class="tm-product-card-price">Rs:{{item.item.discount_price}}</div>
                              {% else %}
                                  <div class="tm-product-card-price">Rs:{{item.item.price}}</div>}
                              {% endif %}
                            </div>
                            <div class="tm-product-card-add">
                                <a href="{{ item.get_add_to_cart_url }}" style="color:white; decoration:none;"><button class="uk-button uk-button-primary tm-product-add-button tm-shine">Add to cart</button></a>
                            </div>
                          </div>
                        </div>
                      </article>

                    </div>
                {% endfor %}
                </div>

              </div>
            </div>
          </div>
        </section>
      </main>
{% endblock content %}

store/templates/store/item_list.html
{% extends "store/base.html" %}
{% block content %}

<h2>Here is the list of items</h2>
{% for item in object_list %}

    <p> {{ item.title}} product name</p>
    <img src="{{ item.image.url }}" alt="IMG-PRODUCT" style="height: 360px;"> <p>product image</p>
    <p> Rs:{{ item.price}} product price</p>

  {% endfor %}


<div class="uk-grid-collapse uk-child-width-1-3 tm-products-grid js-products-grid" uk-grid>
                                {% for item in object_list %}
                                  <article class="tm-product-card">
                                    <div class="tm-product-card-media">
                                      <div class="tm-ratio tm-ratio-4-3"><a class="tm-media-box" href="product.html">
                                          <div class="tm-product-card-labels"><span class="uk-label uk-label-warning">top selling</span><span class="uk-label uk-label-danger">trade-in</span>
                                          </div>
                                          <figure class="tm-media-box-wrap"><img src="{{ item.image.url }}" alt="{{ item.title }}"/>
                                          </figure></a></div>
                                    </div>
                                    <div class="tm-product-card-body">
                                      <div class="tm-product-card-info">
                                        <div class="uk-text-meta uk-margin-xsmall-bottom">{{ item.category }}</div>
                                        <h3 class="tm-product-card-title"><a class="uk-link-heading" href="product.html">{{ item.title }}</a></h3>
                                        <ul class="uk-list uk-text-small tm-product-card-properties">
                                          <li><span class="uk-text-muted">Diagonal display: </span><span>15.4"</span></li>
                                          <li><span class="uk-text-muted">CPU: </span><span>Intel®&nbsp;Core™ i7</span></li>
                                          <li><span class="uk-text-muted">RAM: </span><span>16&nbsp;GB</span></li>
                                          <li><span class="uk-text-muted">Video Card: </span><span>AMD Radeon Pro 555</span></li>
                                        </ul>
                                      </div>
                                      <div class="tm-product-card-shop">
                                        <div class="tm-product-card-prices">
                                          <del class="uk-text-meta">Rs.{{ item.price }}</del>
                                          <div class="tm-product-card-price">Rs.{{ item.discount_price }}</div>
                                        </div>
                                        <div class="tm-product-card-add">
                                          <div class="uk-text-meta tm-product-card-actions"><a class="tm-product-card-action js-add-to js-add-to-favorites tm-action-button-active js-added-to" title="Add to favorites"><span uk-icon="icon: heart; ratio: .75;"></span><span class="tm-product-card-action-text">Add to favorites</span></a><a class="tm-product-card-action js-add-to js-add-to-compare tm-action-button-active js-added-to" title="Add to compare"><span uk-icon="icon: copy; ratio: .75;"></span><span class="tm-product-card-action-text">Add to compare</span></a></div>
                                          <button class="uk-button uk-button-primary tm-product-card-add-button tm-shine js-add-to-cart"><span class="tm-product-card-add-button-icon" uk-icon="cart"></span><span class="tm-product-card-add-button-text">add to cart</span>
                                          </button>
                                        </div>
                                      </div>
                                    </div>
                                  </article>
</div>
{% endfor %}
{% endblock content%}

store/templates/store/order_summary.html
{% extends "store/base.html" %}

{% block content %}
  <main>
    <div class="container">

    <div class="table-responsive text-nowrap">
    <h2>Order Summary</h2>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Item title</th>
            <th scope="col">Price</th>
            <th scope="col">Quantity</th>
            <th scope="col">Total Item Price</th>
        </tr>
        </thead>
        <tbody>
        {% for order_item in object.items.all %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ order_item.item.title }}</td>
            <td>{{ order_item.item.price }}</td>
            <td>
                <a href="{% url 'store:remove-single-item-from-cart' order_item.item.slug %}">-</a>
                {{ order_item.quantity }}
                <a href="{% url 'store:add-to-cart' order_item.item.slug %}">+</a>
            </td>
            <td>
            {% if order_item.item.discount_price %}
                ${{ order_item.get_total_discount_item_price }}
                <span class="badge badge-primary">Saving ${{ order_item.get_amount_saved }}</span>
            {% else %}
                ${{ order_item.get_total_item_price }}
            {% endif %}
            <a style='color: red;' href="{% url 'store:remove-from-cart' order_item.item.slug %}">
                <i class="fas fa-trash float-right"></i>
            </a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan='5'>Your cart is empty</td>
        </tr>
        <tr>
            <td colspan="5">
            <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
            </td>
        </tr>
        {% endfor %}
        {% if object.coupon %}
        <tr>
            <td colspan="4"><b>Coupon</b></td>
            <td><b>-${{ object.coupon.amount }}</b></td>
        </tr>
        {% endif %}
        {% if object.get_total %}
        <tr>
            <td colspan="4"><b>Order Total</b></td>
            <td><b>${{ object.get_total }}</b></td>
        </tr>
        <tr>
            <td colspan="5">
            <a class='btn btn-warning float-right ml-2' href='/checkout/'>Proceed to checkout</a>
            <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
            </td>
        </tr>
        {% endif %}
        </tbody>
    </table>

    </div>

    </div>
  </main>

{% endblock content %}
