dawaiwala/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('frontend/', include('frontend.urls')),
    path('users/', include('users.urls')),
    path('vendors/', include('vendors.urls')),
    path('api/', include('rest_api.urls')),
    path('', include('store.urls')),
]


store/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from. import views
app_name = 'store'

urlpatterns = [
    path('', views.home, name='store'),
    path('about/', views.about, name='store-about'),
    path('blog/', views.blog, name='store-blog'),
    path('brands/', views.brands, name='store-brands'),
    path('catalog/', views.catalog, name='store-catalog'),
    path('category/', views.category, name='store-category'),
    path('contacts/', views.contacts, name='store-contacts'),
    path('delivery/', views.delivery, name='store-delivery'),
    path('news/', views.news, name='store-news'),
    path('faq/', views.faq, name='store-faq'),
    path('settings/', views.settings, name='store-settings'),


    # path('payment/<payment_option>/', views.PaymentView.as_view(), name='store-payment'),
    path('add-to-compare/<slug>/', views.add_to_compare, name='add-to-compare'),
    path('compare/', views.compare, name='store-compare'),
    path('product/<slug>/', views.product, name='store-product'),
    path('add-to-favorite/<slug>/', views.add_to_favorite, name='add-to-favorite'),
    path('favorites/', views.favorites, name='store-favorites'),
    path('cart/', views.CartView.as_view(), name='store-cart'),
    path('subcategory/', views.shop_view, name='store-subcategory'),

    path('add-to-cart/<slug>/', views.add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/', views.remove_from_cart, name='remove-from-cart'),
    path('remove-single-item-from-cart/<slug>/', views.remove_single_item_from_cart, name='remove-single-item-from-cart'),
    path('category/<slug>/', views.category_view, name='store-category'),
    path('review/<int:pk>/', views.review, name='store-review'),
    path('review/delete/<int:pk>/', views.review_delete, name='store-review-delete'),
    path('product/return/<str:status>/<int:pk>/', views.product_refund, name='store-product-return'),
    path('product/cancel/<int:pk>/', views.product_canceled, name='store-product-cancel'),
    path('product/prescription/upload/', views.prescription_upload, name='store-product-prescription-upload'),
    path('address/', views.customer_address_add, name='store-address'),
    path('address/update/<int:pk>/', views.customer_address_update, name='store-address-update'),
    path('checkout/', views.checkout, name='store-checkout'),
    path('payment/stripe/<int:pk>/', views.PaymentView.as_view(), name='store-payment-stripe'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)




vendors/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from . import views

urlpatterns = [
    path('sales/', views.sales, name='vendors-sales'),

    path('products/', views.products_display, name='vendors-products'),
    path('products/add/', views.products_add, name='vendors-products-add'),
    path('products/add/<str:var_id>', views.product_varient_add, name='vendors-products-add-varient'),
    path('products/update/<int:pk>', views.products_update, name='vendors-products-update'),
    path('products/delete/<int:pk>', views.product_delete, name='vendors-products-delete'),

    path('product/<int:pk>/', views.product_sell, name='vendor-product-sell'),

    path('products/ordered/', views.products_ordered, name='vendors-products-ordered'),
    path('products/ordered/update/<int:pk>/', views.products_ordered_update, name='vendors-products-ordered-update'),

    path('products/returned/', views.products_returned, name='vendors-products-returned'),
    path('products/returned/update/<int:pk>/', views.products_returned_update, name='vendors-products-returned-update'),

    path('products/canceled/', views.products_canceled, name='vendors-products-canceled'),
    path('products/canceled/update/<int:pk>/', views.products_cancel_update, name='vendors-products-canceled-update'),


    path('category/', views.category_display, name='vendors-category'),
    path('category/add/', views.category_add, name='vendors-category-add'),

    path('brand/', views.brand_display, name='vendors-brand'),
    path('brand/add/', views.brand_add, name='vendors-brand-add'),

    path('address/add/', views.vendor_address, name='vendors-address-add'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/models.py
from django.db import models
from django.contrib.gis.db import models as geo_models
from django.db.models.signals import post_save
from django.core.validators import MaxValueValidator
from django.utils import timezone
from django.utils.timezone import timedelta

from users.models import User
from vendors.models import Item, Category, Vendor


# Create your models here.
REVIEW_RATING_CHOICES = (
    ('1', 'Terrible'),
    ('2', 'Poor'),
    ('3', 'Average'),
    ('4', 'Very Good'),
    ('5', 'Excellent'),
)


ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)

ORDER_STATUS = (
    ('Preparing Order', 'Preparing Order'),
    ('Shipping', 'Shipping'),
    ('Picked up from store', 'Picked up from store'),
    ('Out for delivery', 'Out for delivery'),
    ('Delivered', 'Delivered'),
    ('RETURNED', 'RETURNED'),
    ('CANCELED', 'CANCELED')
)


RETURN_STATUS = (
    ('Return Denied', 'Return Denied'),
    ('Processing Return Request', 'Processing Return Request'),
    ('Item Picked up', 'Item Picked up '),
    ('Item Received Vendor', 'Item Received Vendor'),
    ('Return Granted', 'Return Granted'),
    ('CANCELED', 'CANCELED')
)

REQUEST_RETURN_TYPE = (
     ('RETURN', 'RETURN'),
     ('Exchange', 'Exchange')
)


RETURN_REASON = (
    ('Damaged', 'Damaged'),
    ('Expired', 'Expired'),
    ('Ordered Wrong Item', 'Ordered Wrong Item'),
    ('Received Wrong Item', 'Received Wrong Item'),
    ('Received Wrong Brand Item', 'Received Wrong Brand Item'),  # may be variation
    ('Other', 'Other')
)


REQUEST_CANCEL_TYPE = (
     ('CANCEL', 'CANCEL'),
     ('Exchange', 'Exchange')
)


CANCEL_REASON = (
    ('', ''),
    ('Not Needed', 'Not Needed'),
    ('Ordered Wrong Product', 'Ordered Wrong Product'),
    ('Receiving To Late', 'Receiving To Late'),
    ('Select Different Payment Method', 'Select Different Payment Method'),
    ('Other', 'Other')
)

CANCEL_STATUS = (
    ('Not Seen by Vendor', 'Not Seen by Vendor'),
    ('CANCEL Denied', 'CANCEL Denied'),
    ('Processing Cancel Request', 'Processing Cancel Request'),
    ('Cancel Granted', 'Cancel Granted'),
)


class UserProfile(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE)
    stripe_customer_id = models.CharField(max_length=50, blank=True, null=True)
    one_click_purchasing = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


def userprofile_receiver(sender, instance, created, *args, **kwargs):
    if created:
        userprofile = UserProfile.objects.create(user=instance)


post_save.connect(userprofile_receiver, sender=User)


class CustomerLocation(geo_models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    order_ref_number = models.CharField(unique=True, max_length=15, null=True)  # or vendor name here
    location = geo_models.PointField(help_text="Use map widget for point the house location")

    def __str__(self):
        return f"{self.location} point location"

    class Meta:
        verbose_name_plural = 'Customer Locations'


# class Addresss(models.Model):
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#     location = models.ForeignKey(CustomerLocation, on_delete=models.CASCADE, null=True)
#
#     street_address = models.CharField(max_length=100)
#     apartment_address = models.CharField(max_length=100)
#
#     city = models.TextField(default='Jalgaon')
#     phone_number = models.BigIntegerField(validators=[MaxValueValidator(9999999999)], blank=True)
#     postal_code = models.IntegerField(validators=[MaxValueValidator(9999999999)])
#
#     address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
#     default = models.BooleanField(default=False)
#
#     def __str__(self):
#         return f"{self.user} Address"
#
#     class Meta:
#         verbose_name_plural = 'Addresses'


class CustomerAddress(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    location = models.ForeignKey(CustomerLocation, on_delete=models.CASCADE, null=True)

    billing_street_address = models.CharField(max_length=100, null=True)
    billing_street_address_line_2 = models.CharField(max_length=100, null=True)
    billing_city = models.CharField(max_length=100, null=True)
    billing_phone_number = models.BigIntegerField(validators=[MaxValueValidator(9999999999)], null=True)
    billing_postal_code = models.IntegerField(validators=[MaxValueValidator(9999999999)], null=True)

    shipping_street_address = models.CharField(max_length=100, null=True)
    shipping_street_address_line_2 = models.CharField(max_length=100, null=True)
    shipping_city = models.CharField(max_length=100, null=True)
    shipping_phone_number = models.BigIntegerField(validators=[MaxValueValidator(9999999999)], null=True)
    shipping_postal_code = models.IntegerField(validators=[MaxValueValidator(9999999999)], null=True)

    shipping_is_billing = models.BooleanField(default=True)
    default = models.BooleanField(default=True)

    def __str__(self):
        try:
            return f"{self.user.first_name}_Address"
        except:
            return f"{self.user}_Address"


class Slide(models.Model):
    caption = models.CharField(max_length=100)
    image = models.ImageField(help_text="Size: 1920x570")
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.caption


class OrderItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()

    def get_total_quantity(self):
        return self.quantity


class FavoriteItem(models.Model):
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    is_fav = models.BooleanField(default=False)

    def __str__(self):
        return f"Favorite {self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()

    def get_total_quantity(self):
        return self.quantity


class CompareItem(models.Model):
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE)

    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    is_cmp = models.BooleanField(default=False)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"Compare {self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()

    def get_total_quantity(self):
        return self.quantity


class Coupon(models.Model):
    code = models.CharField(max_length=15, unique=True)
    discount_percent = models.FloatField()
    minimum_order_amount = models.FloatField()

    def __str__(self):
        return self.code


class PrescriptionUpload(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    prescription = models.ImageField()

    def __str__(self):
        return f"{self.user}_PrescriptionUpload"


class MiniOrder(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    vendor = models.ForeignKey(Vendor, on_delete=models.CASCADE)

    order_item = models.ForeignKey(OrderItem, on_delete=models.CASCADE)

    order_ref_number = models.CharField(default='ORD-100000', max_length=15)
    mini_order_ref_number = models.CharField(unique=True, default='MORN-100000', max_length=15)

    ordered_date = models.DateField()
    ordered_time = models.TimeField()
    ordered = models.BooleanField(default=False)
    order_status = models.CharField(choices=ORDER_STATUS, max_length=50, default='Preparing Order')

    # received_by_customer = models.BooleanField(default=False, blank=True, null=True)
    delivered = models.BooleanField(default=False, blank=True, null=True)
    return_requested = models.BooleanField(default=False)
    return_granted = models.BooleanField(default=False)

    return_window = models.DateTimeField(default=timezone.now) # () + timedelta(days=10)
    return_status = models.CharField(choices=RETURN_STATUS, max_length=50, default='')


vendors/forms.py
from django import forms
from .models import VendorLocation
from mapwidgets.widgets import GooglePointFieldWidget

from .models import Item, Category, Brands, VendorAddress, SameItem
from store.models import Order, MiniOrder


class ItemForm(forms.ModelForm):
    image_2 = forms.ImageField(required=False)
    image_3 = forms.ImageField(required=False)
    image_4 = forms.ImageField(required=False)
    image_5 = forms.ImageField(required=False)
    short_description = forms.CharField(required=False)
    description = forms.Textarea()
    key_benefits = forms.Textarea()
    direction_for_use = forms.Textarea()
    safety_information = forms.Textarea()

    class Meta:
        model = Item
        fields = ('category', 'brand', 'title', 'price', 'discount_price', 'label', 'stock_no', 'short_description',
                  'description', 'key_benefits', 'direction_for_use', 'safety_information', 'is_active', 'image_main',
                  'image_2', 'image_3', 'image_4', 'image_5', 'has_variation')


class SameItemForm(forms.ModelForm):

    class Meta:
        model = SameItem
        fields = ('stock_no', )


class ItemVariationsForm(forms.ModelForm):
    image_2 = forms.ImageField(required=False)
    image_3 = forms.ImageField(required=False)
    image_4 = forms.ImageField(required=False)
    image_5 = forms.ImageField(required=False)

    class Meta:
        model = Item
        fields = ('title', 'price', 'discount_price', 'label', 'stock_no', 'short_description', 'description',
                  'key_benefits', 'direction_for_use', 'safety_information', 'is_active', 'image_main', 'image_2',
                  'image_3', 'image_4', 'image_5')


class CategoryForm(forms.ModelForm):
    image = forms.ImageField(required=False)  # image of slide ...

    class Meta:
        model = Category
        fields = ('title', 'description', 'is_active', 'image')


class OrderForm(forms.ModelForm):

    class Meta:
        model = MiniOrder
        fields = ('order_status',)


class ReturnForm(forms.ModelForm):

    class Meta:
        model = MiniOrder
        fields = ('return_status', 'return_granted')


class CancelForm(forms.ModelForm):

    class Meta:
        model = MiniOrder
        fields = ('cancel_status', 'cancel_granted')


class BrandsForm(forms.ModelForm):
    brand_image = forms.ImageField(required=False)

    class Meta:
        model = Brands
        fields = ('brand_name', 'brand_image')


class LocationForm(forms.ModelForm):

    class Meta:
        model = VendorLocation
        fields = ("location",)
        widgets = {
            'location': GooglePointFieldWidget,
            # 'name': GoogleStaticOverlayMapWidget,
        }


class VendorAddressForm(forms.ModelForm):
    class Meta:
        model = VendorAddress
        fields = ('street_address', 'apartment_address', 'city', 'postal_code')

vendors/templates/vendors/bs4_form.html
{% load widget_tweaks %}

{% for hidden_field in form.hidden_fields %}
  {{ hidden_field }}
{% endfor %}

{% if form.non_field_errors %}
  <div class="alert alert-danger" role="alert">
    {% for error in form.non_field_errors %}
      {{ error }}
    {% endfor %}
  </div>
{% endif %}

{% for field in form.visible_fields %}
  <div class="form-group">
    {{ field.label_tag }}

    {% if form.is_bound %}
      {% if field.errors %}
        {% render_field field class="form-control is-invalid" %}
        {% for error in field.errors %}
          <div class="invalid-feedback">
            {{ error }}
          </div>
        {% endfor %}
      {% else %}
        {% render_field field class="form-control is-valid" %}
      {% endif %}
    {% else %}
      {% render_field field class="form-control" %}
    {% endif %}

    {% if field.help_text %}
      <small class="form-text text-muted">{{ field.help_text }}</small>
    {% endif %}
  </div>
{% endfor %}

vendors/templates/vendors/test.html
{% extends 'store/base.html' %}
{% load static %}
{% block content %}



 <section class="uk-section uk-section-small">
          <div class="uk-container">
            <div class="uk-grid-large" uk-grid>
              <div class="uk-width-1-1 uk-width-1-1@m tm-aside-column">
                <div class="uk-card uk-card-default uk-card-small tm-ignore-container" uk-sticky="offset: 90; bottom: true; media: @m;"></div>
                </div>
              </div>



          <div class="uk-grid-medium uk-child-width-1-2@s " uk-grid>

                <div class="w-75">



                <div class="uk-card uk-card-default uk-card-body">
                    <h1 class="uk-h2">Shipment Details</h1><hr>
                        <h6># {{order.order_ref_number}}</h6>
                    <hr>

                                <table class="uk-table uk-table-divider uk-table-hover" cellpadding="8px" border="0">

                                    <tr> <th>Product</th>
                                        <th>Order Date</th><th>Cancel Date</th><th>Ouantity</th> <th>Item Price</th> <th>Order Total</th>
                                    </tr>
                                    {% for item in order.items.all %}
                                            <tr> <td  align="left"><img src="{{mini_order.order_item.item.image_main.url}}" width="35px">&nbsp&nbsp {{item.item.title}}</td>


                                                <td>{{ order.ordered_date}}</td>
                                                {% for x in order.mini_order.all%}
                                                <td>{{x.return_window}}</td>
                                                {% endfor %}


                                                <td align="center">{{ item.quantity }}</td>
                                                {% if item.item.discount_price %}
                                                    <td align="left">{{item.item.discount_price}}</td>
                                                {% else %}
                                                    <td align="left">{{item.item.price}}</td>
                                                {% endif  %}

                                                <td align="left">{{item.get_final_price}}</td>
                                            </tr>
                                </table>
    {% endfor %}                                <hr />

                </div>
                    <br>

                    <div class="w-100 mt-10">
                    <div class="uk-card uk-card-default uk-card-body">
                        <h3 align="left">Summary</h3>
                        <hr>
{% for item in order.items.all %}
                        <table class="p-15" cellpadding="8px">
                            <tr>
                                <td align="left" width="90%">Subtotal</td>
                                <td align="right">Rs.{{item.item.price}}</td>
                            </tr>

                               <tr>
                                <td align="left">Discount Price</td>
                                <td align="right">Rs.{{item.item.discount_price}}</td>
                            </tr>

                            <tr>
                                <td align="left">Shipping</td>
                                <td align="right">Rs.0.0</td>
                            </tr>

                               <tr>
                                   <td align="left" width="90%"><b>Total</b></td>
                                   <td align="right"><b>Rs.{{item.get_final_price}}</b></td>
                            </tr>

                        </table>
                        {% endfor %}
                        <hr>
                        <table>
                            <tr>
                                <th width="90%">
                                   <h5>Prescription Uploaded</h5>
                                </th>
{% for y in order.items.all %}
                                {% if y.prescription %}
                                <th><div class="uk-inline">
                                                <img src="{{y.prescription.prescription.url}}" width="100px" type="button"></button>
                                                <div uk-drop="pos: top-right">
                                                    <div class="uk-card uk-card-body uk-card-default"><img src="{{y.prescription.prescription.url}}" width="100%"></div>
                                                </div>
                                            </div></th>
                                {% else %}
                                <th>
                                    <td align="right">No Prescription uploaded</td>
                                </th>
                                {% endif %}
                                {% endfor %}
                            </tr>
                        </table>

                    </div>
                  </div>
            </div>

                <div class="w-25">
                <div class="uk-card uk-card-default uk-card-body">

                   <h1 class="uk-h2">Customer</h1><hr>

                    <a align="left">{{order.user.username}}</a>
                    <hr>
                    <br>
                    <h5><b>Payment Method</b></h5>
                    {{mini_order.payment_method}}
                    <hr>

<br>
                    <h6 align="left"><b>SHIPPING ADDRESS</b></h6>
                    <br>
                    <table >
                    <tr><td align="left">{{order.address.shipping_street_address}}</td>  </tr>
                        <tr> <td align="left">{{order.address.shipping_street_address_line_2}}</td>  </tr>
                    <tr> <td>{{order.address.shipping_city}}</td>  </tr>
                    <tr> <td>{{order.address.shipping_phone_number}}</td>  </tr>
                    <tr> <td>{{order.address.shipping_postal_code}}</td>  </tr>


                    </table>
                    <hr>
                    <br>
                    <h6 align="left"><b>BILLING ADDRESS</b></h6>
                    <br>
                    <table align="left">
                        <tr>    <td align="left">{{order.address.billing_street_address}}</td>      </tr>
                                            <tr><td align="left">{{order.address.billing_street_address_line_2}}</td>   </tr>
                                            <tr>    <td align="left">{{order.address.billing_city}}</td> </tr>
                                            <tr>    <td align="left">{{order.address.billing_phone_number}}</td> </tr>
                                             <tr> <td>{{order.address.billing_postal_code}}</td>  </tr>

                    </table>


                </div>
            </div>



         </div>






        </section>








  <div class="uk-width-1-1 uk-width-expand@m">
    <div class="uk-card uk-card-default uk-card-small tm-ignore-container">
      <header class="uk-card-header">
        <h1 class="uk-h2">Orders</h1>
      </header>
      <section class="uk-card-body">
          <h3>Order Details</h3>
            <table style="margin-left:2em;">
                <a href="#">Invoice</a>
                <tr> <th> Order Number: {{order.order_ref_number}}</th> </tr>
                    <tr>  <td> <b>Contact Details</b> </td> </tr>
                    <tr>    <td>{{order.user.first_name}}&nbsp;{{order.user.last_name}}</td> </tr>
                    <tr>    <td>{{order.shipping_address.phone_number}}</td> </tr>
                    <tr> <td><br></td> </tr>

                    <tr>  <td> <b>Shipping Address</b> </td> </tr>
                    <tr>    <td>{{order.shipping_address.street_address}}</td>  </tr>
                    <tr>    <td>{{order.shipping_address.apartment_address}}</td>  </tr>
                    <tr>    <td>{{order.shipping_address.city}}&nbsp;{{order.shipping_address.postal_code}}</td>  </tr>
                    <tr> <td><br></td> </tr>

                    <tr>  <td> <b>Billing Address</b> </td> </tr>
                     <tr>    <td>{{order.billing_address.street_address}}</td>      </tr>
                    <tr>    <td>{{order.billing_address.apartment_address}}</td>   </tr>
                    <tr>    <td>{{order.billing_address.city}}&nbsp;{{order.billing_address.postal_code}}</td> </tr>
                    <tr> <td><br></td> </tr>

                    <tr>  <td> <b>Payment Method</b> </td> </tr>
                    <tr>    <td>{{order.payment_method}}</td>      </tr>
            </table>
          <hr>
         <table class="uk-table uk-table-small uk-table-justify uk-table-responsive ">
          <tbody>
            <tr>
              <th class="uk-width-small uk-text-muted uk-text-small">Order Placed On</th>
              <th class="uk-width-small uk-text-muted uk-text-small">Total</th>
              <th class="uk-width-small uk-text-muted uk-text-small">Ship to</th>
              <th class="uk-width-large uk-text-muted uk-text-small">{{ order.order_ref_number }}</th>
            </tr>

            <tr>
              <td class="uk-width-small uk-text-muted uk-text-small">{{order.ordered_date}}</td>
              <td class="uk-width-small uk-text-muted uk-text-small">Rs:{{order.payment.amount}}</td>
              <td class="uk-width-small uk-text-muted uk-text-small">{{order.user.first_name}}</td>
              <td class="uk-width-large uk-text-muted uk-text-small">-</td>
            </tr>
          </tbody>
        </table>
        <hr>
        <table class="uk-table uk-table-small uk-table-justify uk-table-responsive uk-table-divider uk-margin-small-top uk-margin-remove-bottom">
          <tbody>
          {% for item in order.items.all %}
            <tr>
              <th><img src="{{item.item.image_main.url}}" style="width:8em;"></th>
              <td>
                <h4>{{item.item.title}}</h4>
                <span class="uk-text-muted uk-text-small"> Sold by:{{item.item.sold_by.user.first_name}}</span><br>
                <span class="uk-text-muted uk-text-small">Rs:{{item.get_final_price}}</span><br>
                <h3 class="tm-product-card-title"><a class="uk-link-heading" href="{% url 'store:store-product' item.item.id %}">Buy it again?</a></h3>
                <h3 class="tm-product-card-title"><a class="uk-link-heading" href="{% url 'store:store-review' item.item.id %}">Write a review</a></h3>
              </td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </section>
    </div>
  </div>
{% endblock %}